"""redesign flat occupancy architecture

Revision ID: 44ba813533a9
Revises: 4f61fd4767b0
Create Date: 2026-07-01 16:10:22.452640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ba813533a9'
down_revision: Union[str, Sequence[str], None] = '4f61fd4767b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat_occupancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_type', sa.Enum('owner', 'tenant', 'family', 'caretaker', name='occupancytype'), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], name='fk_occupancy_flat_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_occupancy_user_id', use_alter=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='fk_verified_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_occupancies_id'), 'flat_occupancies', ['id'], unique=False)
    op.add_column('flats', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('flats', 'tenant_id')
    op.drop_column('flats', 'owner_id')
    op.create_foreign_key('fk_society_admin_id', 'societies', 'users', ['admin_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('users_flat_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'flat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_flat_id_fkey'), 'users', 'flats', ['flat_id'], ['id'])
    op.drop_constraint('fk_society_admin_id', 'societies', type_='foreignkey')
    op.add_column('flats', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flats', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('flats', 'is_active')
    op.drop_index(op.f('ix_flat_occupancies_id'), table_name='flat_occupancies')
    op.drop_table('flat_occupancies')
    # ### end Alembic commands ###
